kind: PersistentVolume
apiVersion: v1
metadata:
  name: data
  labels:
    type: local
    id: mysql-data
spec:
  storageClassName: ""
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/k8s-mysql-data"
    type: DirectoryOrCreate
